#!/usr/bin/env bash
# install-git-hooks.sh — install the gitleaks-backed pre-commit secret gate.
#
# .git/hooks is NOT tracked by git, so a fresh clone has no hooks. Run this once
# after cloning to wire up the staged-secret scan:
#
#     bash scripts/install-git-hooks.sh
#
# The hook blocks any commit whose STAGED diff contains a secret (HF token, API
# key, high-entropy string, ...), per .gitleaks.toml. Requires the `gitleaks`
# binary on PATH (https://github.com/gitleaks/gitleaks/releases). If gitleaks is
# absent the hook warns loudly and does NOT silently pass.
#
# Origin: 2026-05-23 — a live HF token leaked via a `${HF_TOKEN:-<literal>}`
# fallback in scripts/pod_quant_31b.sh, pushed to this public repo. This gate
# makes that class of mistake un-committable.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# AUTO-GENERATED by scripts/install-git-hooks.sh — gitleaks staged-secret gate.
# Edit the generator, not this file (it is overwritten on re-install).
REPO_ROOT="$(git rev-parse --show-toplevel)"

if ! command -v gitleaks >/dev/null 2>&1; then
    echo "⚠ gitleaks not found on PATH — STAGED SECRET SCAN SKIPPED." >&2
    echo "  Install it, then re-run: bash scripts/install-git-hooks.sh" >&2
    echo "  (Refusing to silently allow an unscanned commit would block all work;" >&2
    echo "   this is a loud warning instead. Install gitleaks to restore the gate.)" >&2
    exit 0
fi

# Scan only the staged diff (fast; good for pre-commit). --redact keeps any
# detected secret out of the terminal/log output.
if ! gitleaks git --staged --redact --no-banner -c "$REPO_ROOT/.gitleaks.toml"; then
    echo >&2
    echo "✖ gitleaks: a secret was detected in your STAGED changes — commit aborted." >&2
    echo "  • Never hardcode a token. Use an env var that fails loud if unset:" >&2
    echo "        export HF_TOKEN=\"\${HF_TOKEN:?HF_TOKEN must be exported}\"" >&2
    echo "  • If this is a genuine false positive, add an allowlist entry to" >&2
    echo "    .gitleaks.toml and re-stage." >&2
    exit 1
fi
HOOK_EOF

chmod +x "$HOOK"
echo "✓ installed pre-commit hook → $HOOK"
if command -v gitleaks >/dev/null 2>&1; then
    echo "✓ gitleaks present: $(gitleaks version)"
else
    echo "⚠ gitleaks NOT on PATH — install it so the hook can actually scan:"
    echo "    https://github.com/gitleaks/gitleaks/releases  (binary → /usr/local/bin/gitleaks)"
fi
